server:
  port: 8080 # default
  shutdown: graceful
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  main:
    banner-mode: off
    lazy-initialization: true
    web-application-type: reactive
  jackson:
    time-zone: UTC
    locale: en_US
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/asepay?currentSchema=asepay" #for local solution replace 'postgres-a2b' with localhost and port '5432' to '5433'
    username: "asepay_user"
    password: "asepay_password"
    hikari:
      minimumIdle: 4 # default: same as maximumPoolSize
      maximumPoolSize: 8 # cores * 2; default is 10
      connection-timeout: 35000 #default 30000
      pool-name: "hikari-pool"
      idle-timeout: 10000 # default: 600000 (10 minutes)
      max-lifetime: 35000 # default: 1800000 (30 minutes)
      keepaliveTime: 30000 # default: 0 (disabled)
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: "asepay"
        types:
          print:
            banner: false
  flyway:
    schemas: asepay
    table: schema_version
    locations:
      - classpath:db/migrations/2023
    user: "asepay_user"
    password: "asepay_password"

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      show-components: always
      show-details: always
      group:
        readiness:
          include: readinessState, db
  endpoints.web.exposure.include: "*"
  prometheus:
    metrics:
      export:
        enabled: true

logging.level:
  ROOT: info
  by.vk.catalog: info
  org.springframework: info
  reactor.netty.http.client: info

springdoc:
  show-actuator: true
  api-docs:
    enabled: false
    groups:
      enabled: false
