version: "3.8"

services:

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=asepay
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
