name: Catalog Service CI/CD

on:
  push:
    branches: [ "master", "feature/**" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        id: setup-gradle
        with:
          gradle-version: current
      - run: ./gradlew --parallel --no-daemon compileJava -q
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        id: setup-gradle
        with:
          gradle-version: current
      - run: ./gradlew --parallel --no-daemon test -q
  build:
    runs-on: ubuntu-latest
    needs: [ "compile", "tests" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        id: setup-gradle
        with:
          gradle-version: current
      - run: ./gradlew --parallel --no-daemon build -x check -q
  delivery:
    runs-on: ubuntu-latest
    needs: [ "build" ]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        id: setup-gradle
        with:
          gradle-version: current
      - run: ./gradlew --parallel --no-daemon jibDockerBuild -x check -q
      - uses: anchore/scan-action@v3
        with:
          image: "gcr.io/template-ase/catalog-service"
          fail-build: false
          severity-cutoff: critical
      - run: ./gradlew --parallel --no-daemon jib -x check -q Djib.to.auth.username=fragaly -Djib.to.auth.password=${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}